<a href="https://colab.research.google.com/github/np03cs4a240070-oss/worksheet1-umikapoudel/blob/main/week1workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1
#Initialize an empty array with size 2X2.
import numpy as np
arr1 = np.empty((2, 2))
print(arr1)

[[3.56025457e-315 0.00000000e+000]
 [4.94065646e-322 6.64685780e-310]]


In [ ]:
#Initialize an all one array with size 4X2.
import numpy as np
arr2 = np.ones((4, 2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
arr3 = np.full((4, 3), 7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr4 = np.zeros_like(a)
print(arr4)

[[0 0 0 0]
 [0 0 0 0]]


In [ ]:
#Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
b = np.array([10, 20, 30])
arr5 = np.ones_like(b)
print(arr5)

[1 1 1]


In [ ]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1, 2, 3, 4, 5]
arr6 = np.array(new_list)
print(arr6)

[1 2 3 4 5]


In [ ]:
# 2
#Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
arr1_range = np.arange(10, 50)
print(arr1_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
c = np.arange(9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Create a 3X3 identity matrix.{Hint:np.eye()}
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
e = np.random.random(30)
print(e.mean())

0.5518920264907874


In [ ]:
#Create a 10X10 array with random values and find the minimum and maximum values.
f = np.random.random((10,10))
print("Min:", f.min(), "Max:", f.max())

Min: 0.014004454564295665 Max: 0.9842622167119727


In [ ]:
#Create a zero array of size 10 and replace 5th element with 1.
g = np.zeros(10)
g[4] = 1
print(g)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1,2,0,0,4,0])
rev = arr[::-1]
print(rev)

[0 4 0 0 2 1]


In [ ]:
#Create a 2d array with 1 on border and 0 inside.
h = np.ones((5,5))
h[1:-1, 1:-1] = 0
print(h)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.
i = np.zeros((8,8), dtype=int)
i[1::2, ::2] = 1
i[::2, 1::2] = 1
print(i)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#3
#For the following arrays:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#Add the two array.
print("sum of x and y\n",x + y)

sum of x and y
 [[ 6  8]
 [10 13]]


In [ ]:
#Subtract the two array.
print("subtraction of x and y \n",x - y)

subtraction of x and y 
 [[-4 -4]
 [-4 -3]]


In [ ]:
#Multiply the array with any integers of your choice.
print("multiplication of x and y \n",x * y)

multiplication of x and y 
 [[ 5 12]
 [21 40]]


In [ ]:
#Find the square of each element of the array.
print("square of x and y \n",x ** y)

square of x and y 
 [[     1     64]
 [  2187 390625]]


In [ ]:
#Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("dot product of v and w \n",np.dot(v, w))
print("dot product of x and v \n",np.dot(x, v))
print("dot product of x and y \n",np.dot(x, y))

dot product of v and w 
 219
dot product of x and v 
 [29 77]
dot product of x and y 
 [[19 22]
 [50 58]]


In [ ]:
#Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.
print("concatenation of x and y along row \n",np.concatenate((x, y), axis=0))
print("concatenation of x and y along column \n",np.concatenate((x, y), axis=1))

concatenation of x and y along row 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
concatenation of x and y along column 
 [[1 2 5 6]
 [3 5 7 8]]


In [ ]:
#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print("concatenation of x and v \n",np.concatenate((x, v), axis=0))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#4
#For the following arrays:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);
#Prove following with Numpy:
#Prove A*A^−1 = I.
invA = np.linalg.inv(A)
K = np.dot(A,invA)
print("A * A inverse =\n", K)

A * A inverse =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#Prove AB ̸= BA.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [ ]:
#Prove (AB)^T = B^T A^T
transposeAB = np.transpose(AB)
tranBtranA= np.dot(np.transpose(B), np.transpose(A))
print("Transpose of (AB)^T:\n", transposeAB)
print("Transpose of B^TA^T:\n", tranBtranA)
print("hence, (AB)^T = B^T A^T")

Transpose of (AB)^T:
 [[23 51]
 [13 29]]
Transpose of B^TA^T:
 [[23 51]
 [13 29]]
hence, (AB)^T = B^T A^T


In [ ]:
#Solve the following system of Linear equation using Inverse Methods.{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9
#Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
A = np.array([[ 2, -3,  1],[ 1, -1,  2],[ 3,  1, -1]])
B = np.array([-1, -3, 9])
inverse= np.linalg.inv(A)
y = np.dot(inverse, B)
print("inverse:\n", y)

inverse:
 [ 2.  1. -2.]
